# Use an official Node.js 19 image as a base
FROM node:19-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the package*.json files / Install dependencies
COPY package*.json ./

# Run npm install 
RUN npm install

# Bundle app source copy the application code
COPY . .

# Expose the port the server will use
EXPOSE 3000

# Run the command to start the server
CMD ["npm", "start"]